plugins: rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'tmp/**/*'

# The defaults for these seem to be based on a rails env, this is not rails.
Metrics/ModuleLength:
  Max: 250

Metrics/ClassLength:
  Max: 250

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 10

# Line length is intentionally unrestricted.
Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'Guardfile'
    - 'Rakefile'
    - 'spec/**/*'

# we exclude these two files since they are generated, the rest of our projects
# should use // style regexps.
Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true
  Exclude:
    - 'Guardfile'
    - '*.gemspec'

# String literal quote style is not enforced.
Style/StringLiterals:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/*'
    - 'exe/*'

# Align hash pairs as tables.
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
