require 'webmock/rspec'

require 'pushover'

include Pushover

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end
def setup_webmocks
  WebMock.reset!
  good_result = '{"status":1}'
  bad_token = '{"token":"invalid","errors":["application token is invalid"],"status":0}'
  bad_user = '{"user":"invalid","errors":["user identifier is invalid"],"status":0}'

  stub_http_request(:post, "https://api.pushover.net/1/messages.json").to_return(:status => 200,
    :headers => {}, :body => good_result).with(:body => hash_including({token:'good_token', user:'good_user'}))
  stub_http_request(:post, "https://api.pushover.net/1/messages.json").to_return(:status => 200,
    :headers => {}, :body => bad_token).with(:body => hash_including({token:'bad_token', user:'good_user'}))
  stub_http_request(:post, "https://api.pushover.net/1/messages.json").to_return(:status => 200,
    :headers => {}, :body => bad_user).with(:body => hash_including({token:'good_token', user:'bad_user'}))
end
