#!/usr/bin/env ruby
require 'pushover'
require 'pry'

argv = "--token='a' --user='b' message goes here".split
index = argv.find_index { |i| !i.start_with? '-' }
env_options = ENV.select { |k, _v| k.start_with? "PUSHOVER_" }.map { |k, v| [k.split("PUSHOVER_").last.downcase, v] }.to_h
@options = argv[0..index - 1].map { |a| a.split(/-+(?<k>\w+)(?>=|)(?>'|"|)(?<v>.*?)(?>'|"|$)/)[1..2] }.to_h.merge(env_options)
@message = argv[index..-1]

puts @options
puts @message
